dist: trusty
env:
  - CTEST_OUTPUT_ON_FAILURE=1
os:
- linux
language: cpp

addons:
  sonarcloud:
    organization: "gordon01"
    token:
      secure: "cqEo/0ERsN5ir81ZSS5BEJloyeViiJapDcPMBvIqPzNBGUGWojVvPW3HxIJMHwQ3x3AlrE+N3rIiezeKODYsmeL5TNDVt/C95ITEgtAohJb1yd3/x65BuZIktGEpyy4X7piyzwMXgenPFLOwBn3pEgC/dQdCukyiNzPlYeQqQBDMnWMk2om9/ZYUDo5iXKtO1akjmSWdMs5RdtT03BLf1vQRpWU8BL0jUZrkxmNZyoNAUSvnXUyxFnuERaUgRKUvLgdx948oY4b+ZPaucOh1B0bG4Mk5QpCmZG97aXIh2b8SaI4s0MXv4Q/omrwxE8mE7EWcvolpiasE9AV0JXs5Sn/hHQwcLDi/8I1Pw2b8D3OheospkrFfNVD8HpxHACxSAKYZRTBGqn5rrbI3cM7xYJQ6qj8IG2itjcQjD7AgkKOmV5kazyFfisqHpI5oN7ycK0ioZCAzlXZ5LBxC7IqZBVdATbmCKGjSF81KE5OWU0dX9a6M97heFRMUyRdhvMoh4oTAaY6fDI5RycuRlHqgDPzmbCl7VzPDWtY6/ZB7Pf3uLyKvYEAOl/mUHZFwaMfG1goJlo6jrwY0o6QZmvlP542raX0EjTXhZN4cSV8y0dXpJKxWfY7ea6qtZZ8G/0AlkkPdFf7EzRkOzZ1Onv7f6laFr93b4lmduvzq7QtG64I="

matrix:
  include:
    - compiler: gcc
      script:
        - mkdir build
        - cd build
        - cmake ../tests
        - build-wrapper-linux-x86-64 --out-dir ../bw-output make all
        - ./tests 
        - find CMakeFiles/tests.dir/ -name 'WVT_Water7.c.*' -type f -print -exec mv -f {} .. \;
        - cd ..
        - gcov lib/WVT_Water7.c --object-file WVT_Water7*gcda --object-file WVT_Water7*gcno
        - sonar-scanner

    - compiler: clang
      script:
        - mkdir build
        - cd build
        - cmake ../tests
        - make all
        - ./tests 
